<a href="https://colab.research.google.com/github/RahmanToufik/MachineLearning_Intro/blob/Master/1hotEncExercise.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
from sklearn.preprocessing import LabelEncoder
from sklearn.linear_model import LinearRegression
model = LinearRegression()
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer

In [2]:
df= pd.read_csv("carprices.csv")
df

                Car Model  Mileage  Sell Price($)  Age(yrs)
0                  BMW X5    69000          18000         6
1                  BMW X5    35000          34000         3
2                  BMW X5    57000          26100         5
3                  BMW X5    22500          40000         2
4                  BMW X5    46000          31500         4
5                 Audi A5    59000          29400         5
6                 Audi A5    52000          32000         5
7                 Audi A5    72000          19300         6
8                 Audi A5    91000          12000         8
9   Mercedez Benz C class    67000          22000         6
10  Mercedez Benz C class    83000          20000         7
11  Mercedez Benz C class    79000          21000         7
12  Mercedez Benz C class    59000          33000         5

In [3]:
df.rename(columns={'Car Model': 'car_model', 'Sell Price($)': 'sell_price', 'Age(yrs)': 'age_yrs'}, inplace=True)
df.head()

  car_model  Mileage  sell_price  age_yrs
0    BMW X5    69000       18000        6
1    BMW X5    35000       34000        3
2    BMW X5    57000       26100        5
3    BMW X5    22500       40000        2
4    BMW X5    46000       31500        4

In [4]:
le = LabelEncoder()

In [5]:
dfle = df
dfle.car_model = le.fit_transform(dfle.car_model)
dfle

    car_model  Mileage  sell_price  age_yrs
0           1    69000       18000        6
1           1    35000       34000        3
2           1    57000       26100        5
3           1    22500       40000        2
4           1    46000       31500        4
5           0    59000       29400        5
6           0    52000       32000        5
7           0    72000       19300        6
8           0    91000       12000        8
9           2    67000       22000        6
10          2    83000       20000        7
11          2    79000       21000        7
12          2    59000       33000        5

In [6]:
model= LinearRegression()

In [7]:
X = dfle.drop(columns = "sell_price", axis = 1)
X

    car_model  Mileage  age_yrs
0           1    69000        6
1           1    35000        3
2           1    57000        5
3           1    22500        2
4           1    46000        4
5           0    59000        5
6           0    52000        5
7           0    72000        6
8           0    91000        8
9           2    67000        6
10          2    83000        7
11          2    79000        7
12          2    59000        5

In [8]:
y = dfle.sell_price.values
y

array([18000, 34000, 26100, 40000, 31500, 29400, 32000, 19300, 12000,
       22000, 20000, 21000, 33000])

In [9]:
model.fit(X,y)

LinearRegression()

In [10]:
model.score(X,y)

0.8719970367825953

In [11]:
model.predict([[2,45000,4]])

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([33336.7721827])

In [12]:
model.predict([[1,86000,5]])

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([15603.56957949])